import { MELEE_COMBOS, comboNotation } from './melee-combos.js';

export function installComboUI() {
  const button = '<button class="text-button" data-action="combos">Enchaînements de coups ↗</button>';
  document.querySelector('#home [data-action="controls"]').insertAdjacentHTML('afterend', button);
  document.querySelector('#controls [data-action="close-controls"]').insertAdjacentHTML('beforebegin', button);
  document.querySelector('#pause [data-action="controls"]').insertAdjacentHTML('afterend', button);
  document.querySelector('#app').insertAdjacentHTML('beforeend', `<section id="combos" class="screen modal-screen" aria-labelledby="combos-title"><div class="modal combo-modal"><p class="eyebrow">FAIS PARLER LA TECHNIQUE</p><h2 id="combos-title">LES <em>ENCHAÎNEMENTS.</em></h2><p class="combo-keys"><b>Poing :</b> J · X / □ &nbsp; <b>Pied :</b> K · Y / △</p><p class="muted">Répète plusieurs fois le même bouton avant de changer : uniquement des poings et des pieds. Appuie séparément sur chaque bouton ; maintenir Poing conserve la rafale simple.</p><div class="combo-list">${MELEE_COMBOS.map(c => `<article tabindex="0"><h3>${c.name}</h3><p class="combo-sequence">${comboNotation(c.steps)}</p><p>${c.description}</p><strong>Dernier coup : +${Math.round(c.bonus * 100)} %</strong></article>`).join('')}</div><p class="combo-rules">Chaque coup doit toucher pour continuer ; tu peux changer de cible. Prépare le prochain bouton pendant l’animation. Tu disposes de 0,7 s après la fin du coup pour poursuivre. Chaque étape réussie ajoute +5 % (maximum +20 %), en plus de la finition ; le bonus total est limité à +95 % des dégâts normaux du coup. Les améliorations restent prises en compte.</p><p class="combo-rules">Un coup reçu, un saut, une esquive, une technique spéciale ou un coup raté interrompt l’enchaînement. Une finition ratée laisse une courte ouverture. Ces enchaînements renforcent les frappes sans projection, charge, mise en hauteur ni collision entre ennemis. Les boss subissent aussi les dégâts bonus. En coop, chaque joueur possède son propre enchaînement.</p><button class="button primary" data-action="close-combos"><span>Retour</span><span>B / ○ ←</span></button></div></section>`);
}
