import { CHAPTERS, fighter } from './data.js';
import { nextDistrict } from './campaign-route.js';
export function installRouteUI(){
 const style=document.createElement('link');style.rel='stylesheet';style.href='/styles/route.css';document.head.append(style);
 const panel=document.createElement('section');panel.id='badges';panel.className='screen route-screen';panel.setAttribute('aria-labelledby','route-title');
 panel.innerHTML=`<div class="route-copy"><p class="route-eyebrow">LE TOUR DE SARAN</p><h1 id="route-title">UN QUARTIER.<br><em>UNE VICTOIRE.</em></h1><p id="route-description" class="route-description"></p><div class="route-count"><strong id="route-count">1<span>/6</span></strong><div><b>QUARTIERS LIBÉRÉS</b><div id="route-dots" aria-hidden="true"></div></div></div><div class="route-next"><small>PROCHAINE ESCALE</small><b id="route-next-name"></b><p>Un nouvel ordre à chaque partie. Aucun quartier en double.</p></div><button class="button primary" data-action="route-next" id="route-next-button">Continuer →</button><p id="route-coop" class="route-coop" role="status" aria-live="polite"></p><button class="text-button" data-action="quit">Sauvegarder et quitter</button></div><div class="boss-poster"><div class="poster-grain"></div><svg class="boss-orbit" viewBox="0 0 680 540" aria-hidden="true"><defs><linearGradient id="orbit-gold"><stop stop-color="#e8ba65"/><stop offset=".5" stop-color="#796843"/><stop offset="1" stop-color="#e8ba65"/></linearGradient></defs><ellipse cx="340" cy="255" rx="214" ry="188"/><ellipse class="orbit-faint" cx="340" cy="255" rx="255" ry="224"/><path d="M340 65 525 160 525 350 340 445 155 350 155 160Z"/><path class="orbit-spokes" d="M340 65V445M155 160 525 350M155 350 525 160"/></svg><div id="route-heads"></div><div class="boss-medallion final-boss"><div class="boss-frame"><img src="/assets/gustavax/gustavax_p.png" alt="Silhouette de Gustavax, boss final"/><span class="boss-lock">VII</span></div><strong>GUSTAVAX</strong><small>L’ULTIME ADVERSAIRE</small><span class="future-tag">NIVEAU 7 · LE DERNIER MOT</span></div><p class="poster-caption">SIX TERRITOIRES. UNE SEULE BANDE.</p></div>`;
 document.querySelector('#app').append(panel);
}
const positions=[[50,12],[77.2,29.6],[77.2,64.8],[50,82.4],[22.8,64.8],[22.8,29.6]];
export function renderRouteUI(s,slot=0){
 if(!s.route)return;const done=s.route.completed,finished=done.length===6,next=nextDistrict(s),player=s.players[slot];
 const key=JSON.stringify([done,s.chapter,s.routeReady,slot]);const root=document.querySelector('#badges');if(root.dataset.render===key)return;root.dataset.render=key;root.classList.toggle('final-unlocked',finished);
 document.querySelector('#route-title').innerHTML=finished?'LE DERNIER<br><em>ADVERSAIRE.</em>':'UN QUARTIER.<br><em>UNE VICTOIRE.</em>';
 document.querySelector('#route-description').textContent=`${CHAPTERS[s.chapter].name} : ${fighter(CHAPTERS[s.chapter].boss).name} est battu. ${finished?'Les six territoires sont à vous.':'La collection s’agrandit. La tournée continue.'}`;
 document.querySelector('#route-count').innerHTML=`${done.length}<span>/6</span>`;
 document.querySelector('#route-dots').innerHTML=Array.from({length:6},(_,i)=>`<i class="${i<done.length?'filled':''}"></i>`).join('');
 document.querySelector('#route-next-name').textContent=CHAPTERS[next].name;
 document.querySelector('#route-heads').innerHTML=CHAPTERS.slice(0,6).map((c,i)=>{const killed=done.includes(i),justWon=i===s.chapter,[x,y]=positions[i],name=fighter(c.boss).name;return `<div class="boss-medallion ${killed?'defeated':'unbeaten'} ${justWon?'new-victory':''}" style="--x:${x}%;--y:${y}%;--boss-color:${c.color}" aria-label="${name}, ${c.name} : ${killed?'battu':'à battre'}"><div class="boss-frame"><img src="/assets/${c.boss}/${c.boss}_p.png" alt=""/><span class="boss-mark">${killed?'✓':'·'}</span></div><strong>${name}</strong><small>${c.short}</small><span class="boss-status">${killed?'BATTU':'À BATTRE'}</span></div>`;}).join('');
 const ready=!!s.routeReady?.[player?.id],button=document.querySelector('#route-next-button');button.disabled=ready;button.textContent=ready?'En attente de ton pote…':finished?'Affronter Gustavax →':'Prochain quartier →';
 document.querySelector('#route-coop').textContent=s.players.length>1?s.players.filter(p=>p.connected!==false).map(p=>`J${p.id} : ${s.routeReady?.[p.id]?'prêt':'à confirmer'}`).join('  ·  '):'Progression sauvegardée · Reprends cette tournée plus tard';
}
