import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';

const baseURL = process.env.TEST_URL || 'http://localhost:3000';
const options = { headless: true };
if (process.env.BROWSER_PATH) options.executablePath = process.env.BROWSER_PATH;
const browser = await chromium.launch(options);
const errors = [], failures = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
context.on('page', p => { p.on('pageerror', e => errors.push(e.message)); p.on('response', r => { if (r.status() >= 400) failures.push(`${r.status()} ${r.url()}`); }); });
await mkdir('test-results', { recursive: true });
const page = await context.newPage();
const waitScreen = (p, screen) => p.waitForFunction(s => window.saranfou?.inspect().screen === s, screen, { timeout: 60000 });
const state = p => p.evaluate(() => window.saranfou.inspect());
try {
  await page.goto(baseURL); await page.screenshot({ path: 'test-results/home.png' }); console.log('Home rendered');
  await page.getByRole('button', { name: /Descendre dans la rue/ }).click();
  await page.getByRole('button', { name: 'Choisir Yanu', exact: true }).click();
  await page.screenshot({ path: 'test-results/selection.png' });
  await page.getByRole('button', { name: /C’est parti/ }).click();
  await waitScreen(page, null); await page.waitForFunction(() => window.saranfou.inspect().state.phase === 'fight');
  console.log('Solo started'); let before = await state(page);
  await page.keyboard.down('ArrowRight'); await page.waitForTimeout(450); await page.keyboard.up('ArrowRight');
  let after = await state(page); assert.ok(after.state.players[0].x > before.state.players[0].x + 60, 'Solo movement');
  await page.keyboard.down('KeyL'); await page.waitForTimeout(200); await page.keyboard.up('KeyL');
  after = await state(page); assert.equal(after.state.players[0].specialState, null, 'Empty energy prevents special activation');assert.equal(after.state.players[0].energy,0);
  await page.keyboard.press('Escape'); await waitScreen(page, 'pause');
  const frozen = (await state(page)).state.tick; await page.waitForTimeout(200); assert.equal((await state(page)).state.tick, frozen, 'Pause freezes game');
  await page.getByRole('button', { name: /Reprendre/ }).click(); await waitScreen(page, null);
  await page.keyboard.down('KeyJ'); await page.waitForTimeout(500); await page.keyboard.up('KeyJ');
  await page.screenshot({ path: 'test-results/gameplay.png' }); console.log('Solo combat and pause checked');
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Quitter la partie', exact: true }).click();
  await page.getByRole('button', { name: /Ramener un pote/ }).click();
  await page.getByRole('button', { name: /Créer un salon/ }).click(); await waitScreen(page, 'lobby');
  console.log('Host lobby opened'); const code = (await state(page)).room;
  const guestContext = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const guest = await guestContext.newPage(); guest.on('pageerror', e => errors.push(e.message));
  await guest.goto(`${baseURL}/?room=${code}`);
  await guest.getByRole('button', { name: /Rejoindre/ }).click(); await waitScreen(guest, 'lobby');
  await guest.locator('#online-fighter').selectOption('jo');
  await page.screenshot({ path: 'test-results/lobby.png' });
  await page.getByRole('button', { name: /Je suis prêt/ }).click();
  await guest.getByRole('button', { name: /Je suis prêt/ }).click();
  await Promise.all([waitScreen(page, null), waitScreen(guest, null)]); console.log('Two clients started');
  await page.waitForFunction(() => window.saranfou.inspect().state.phase === 'fight');
  const duoBefore = await state(page);
  await guest.keyboard.down('ArrowRight'); await guest.waitForTimeout(500); await guest.keyboard.up('ArrowRight');
  await page.waitForTimeout(100);
  const duoAfter = await state(page), guestAfter = await state(guest);
  assert.equal(duoAfter.state.players.length, 2); assert.equal(guestAfter.slot, 1);
  assert.ok(duoAfter.state.players[1].x > duoBefore.state.players[1].x + 60, 'Guest movement reaches host');
  assert.ok(Math.abs(duoAfter.state.players[1].x - guestAfter.state.players[1].x) < 30, 'Shared positions');
  await guest.keyboard.press('Escape'); await Promise.all([waitScreen(page, 'pause'), waitScreen(guest, 'pause')]);
  const pausedTick = (await state(page)).state.tick; await page.waitForTimeout(200); assert.equal((await state(guest)).state.tick, pausedTick);
  await page.getByRole('button', { name: /Reprendre/ }).click(); await Promise.all([waitScreen(page, null), waitScreen(guest, null)]);
  console.log('Shared pause checked'); await guest.reload(); await waitScreen(guest, null); await waitScreen(page, null); console.log('Reconnect checked');
  assert.equal((await state(guest)).slot, 1, 'Reload reconnects same player');
  await page.screenshot({ path: 'test-results/online.png' });
  await guest.keyboard.press('Escape'); await guest.getByRole('button', { name: 'Quitter la partie', exact: true }).click();
  await waitScreen(page, 'pause'); await page.getByRole('button', { name: 'Continuer seul', exact: true }).click();
  await waitScreen(page, null); assert.equal((await state(page)).mode, 'solo'); assert.equal((await state(page)).state.players.length, 1);
  await guestContext.close();
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const phone = await mobile.newPage(); await phone.goto(baseURL); await phone.screenshot({ path: 'test-results/mobile-home.png' });
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No horizontal overflow');
  await phone.getByRole('button', { name: /Descendre dans la rue/ }).click(); await phone.getByRole('button', { name: /C’est parti/ }).click(); await waitScreen(phone, null);
  assert.equal(await phone.locator('#touch-controls').isVisible(), true, 'Touch controls visible');
  await phone.screenshot({ path: 'test-results/mobile-game.png' });
  await mobile.close();
  assert.deepEqual(errors, [], 'No uncaught browser errors'); assert.deepEqual(failures, [], 'No failed resources');
  console.log('PASS: solo, movement, special, pause, online lobby, two clients, shared pause, reload/reconnect, solo fallback, mobile, resources.');
} catch (error) {
  console.error('Browser test failed:', error.message);
  try { console.error(JSON.stringify(await state(page))); await page.screenshot({ path: 'test-results/failure.png', timeout: 3000 }); } catch {}
  process.exitCode = 1;
} finally { if (errors.length) console.error(errors); if (failures.length) console.error(failures); await browser.close(); }
