import test from 'node:test';
import assert from 'node:assert/strict';
import { Simulation } from '../game/simulation.js';
import { shuffledRoute,cleanRoute } from '../game/campaign-route.js';
import { checkpoint,restoreCheckpoint } from '../game/run-save.js';
function game(team=['jo']){return new Simulation(team,0,12345,{randomRoute:true});}
function defeat(g){g.state.stage=5;g.enterStreet();g.state.wave=g.state.waves.length-1;g.state.enemies=[];g.state.spawnQueue=[];g.clearStreet();}
test('random tours visit exactly six different districts, reproducibly by seed',()=>{const seen=new Set(),starts=new Set();for(let seed=0;seed<100;seed++){const route=shuffledRoute(seed);assert.deepEqual(route,shuffledRoute(seed));assert.deepEqual([...route.order].sort(),[0,1,2,3,4,5]);seen.add(route.order.join());starts.add(route.order[0]);}assert.ok(seen.size>30);assert.equal(starts.size,6);assert.equal(game().state.chapter,game().state.route.order[0]);});
test('each boss fills one medallion and final victory requires all six, not the school identity',()=>{const g=game(),seen=[];for(let n=0;n<6;n++){const chapter=g.state.chapter;seen.push(chapter);defeat(g);assert.equal(g.state.phase,'badges');assert.deepEqual(g.state.route.completed,seen);const score=g.state.score;g.clearStreet();assert.equal(g.state.score,score);assert.equal(g.state.route.completed.length,n+1);g.confirmRoute(0);assert.equal(g.state.phase,'intro');if(n===5)assert.equal(g.state.chapter,6);}assert.equal(new Set(seen).size,6);assert.equal(g.state.route.order.length,6);});
test('badges freeze gameplay until both clients confirm, and disconnected players do not deadlock',()=>{const g=game(['jo','yanu']);defeat(g);const x=g.state.players[0].x,hp=g.state.players[0].hp;g.step([{x:1,punch:true}]);assert.equal(g.state.players[0].x,x);assert.equal(g.state.players[0].hp,hp);g.confirmRoute(0);assert.equal(g.state.phase,'badges');g.confirmRoute(1);assert.equal(g.state.phase,'intro');defeat(g);g.state.players[1].connected=false;g.confirmRoute(0);assert.equal(g.state.phase,'intro');});
test('difficulty and waves follow tour position rather than district identity',()=>{const a=game(),b=game();a.state.chapter=0;b.state.chapter=5;a.state.route={order:[0,1,2,3,4,5],completed:[]};b.state.route={order:[5,1,2,3,4,0],completed:[]};a.seed=99;b.seed=99;a.enterStreet();b.enterStreet();assert.deepEqual(a.state.waves,b.state.waves);const x=a.spawnEnemy('remy'),y=b.spawnEnemy('remy');assert.equal(x.hp,y.hp);assert.equal(x.power,y.power);b.state.route={order:[0,1,2,3,4,5],completed:[0,1,2,3,4]};const late=b.spawnEnemy('remy');assert.ok(late.hp>y.hp);});
test('talent milestones depend on tour progress, preserve six-point transformation budget and store actual bosses',()=>{const g=game();for(let n=0;n<6;n++){for(const stage of [0,2]){g.state.stage=stage;g.enterStreet();g.clearStreet();}defeat(g);assert.ok(g.state.players[0].progression.completed.includes(g.state.chapter));g.confirmRoute(0);}assert.equal(g.state.players[0].progression.points,6);assert.equal(g.state.players[0].progression.completed.length,6);});
test('checkpoints preserve shuffle, completed medallions, difficulty and pending board without reroll or duplicated bonuses',()=>{const g=game(['jo','yanu']);defeat(g);g.confirmRoute(0);const saved=checkpoint(g.snapshot()),h=restoreCheckpoint(saved);assert.equal(h.state.phase,'badges');assert.deepEqual(h.state.route,g.state.route);assert.deepEqual(h.state.routeReady,{});const pts=h.state.players[0].progression.points;h.confirmRoute(0);h.confirmRoute(1);assert.equal(h.state.chapter,g.state.route.order[1]);assert.equal(h.state.players[0].progression.points,pts);assert.equal(h.routeDepth(),1);const mid=restoreCheckpoint(checkpoint(h.snapshot()));assert.deepEqual(mid.state.route,h.state.route);assert.deepEqual(mid.state.waves,h.state.waves);});
test('corrupt route imports reject duplicate districts and fabricated or out-of-order completion',()=>{assert.throws(()=>cleanRoute({order:[0,0,2,3,4,5],completed:[]},0,'intro'));assert.throws(()=>cleanRoute({order:[0,1,2,3,4,5],completed:[2]},2,'badges'));assert.throws(()=>cleanRoute({order:[0,1,2,3,4,5],completed:[0,1,2]},0,'intro'));});
