import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../game/simulation.js';
import {applyProfile,TALENTS,spendPoint} from '../game/progression.js';
import {TRANSFORMATION_MILESTONES} from '../game/transformation-rules.js';
import {blankInput,FLOOR} from '../game/data.js';
import {checkpoint,restoreCheckpoint} from '../game/run-save.js';
function arena(branch=0,rank=6){const sim=new Simulation(['gustavax','jo']),p=sim.state.players[0];Object.assign(sim.state,{phase:'fight',enemies:[],props:[],spawnQueue:[]});applyProfile(p,{milestones:TRANSFORMATION_MILESTONES,talents:TALENTS.gustavax.filter(n=>n.branchIndex===branch).slice(0,rank).map(n=>n.id)});Object.assign(p,{x:500,y:550,energy:100,invincible:0});const enemy=(x=580)=>sim.spawnEnemy('remy',{x,y:550,hp:10000,maxHp:10000,invincible:0,speed:0,cooldown:999});return{sim,p,enemy};}
function run(sim,p,time,input={}){for(let t=0;t<time;t+=1/60){sim.state.time+=1/60;if(p.specialState)sim.updateSpecial(p,{...blankInput(),...input},1/60);sim.updateWorld(1/60);}}
test('Gustavax starts with one point, locks branches, respects all 18 durations and has no friendly damage',()=>{assert.equal(new Simulation(['gustavax']).state.players[0].progression.points,1);for(let b=0;b<3;b++)for(let rank=1;rank<=6;rank++){const {sim,p}=arena(b,rank);p.energy=99;assert.equal(sim.activateSpecial(p),false);p.energy=100;assert.equal(sim.activateSpecial(p),true);assert.equal(p.energy,0);assert.equal(spendPoint(p.progression,TALENTS.gustavax.find(n=>n.branchIndex===(b+1)%3).id),null);const ally=sim.state.players[1],hp=ally.hp,d=rank===6?9:rank>=4?7:5;assert.equal(p.specialState.duration,d);run(sim,p,d+.1,{punch:true,kick:true});assert.equal(p.specialState,null);assert.equal(ally.hp,hp);}});
test('demon claws, fire, teleport and ultimate explosion work without ordinary attacks leaking',()=>{const {sim,p,enemy}=arena();const e=enemy(800);sim.activateSpecial(p);sim.step([{...blankInput(),x:1,dodge:true},blankInput()]);assert.ok(p.x>750);assert.equal(p.attack,null);assert.equal(p.action,'special');assert.ok(e.hp<10000);run(sim,p,.7,{kick:true});assert.ok(sim.state.hazards.some(h=>h.gustavaxFire));assert.equal(sim.state.allies.filter(m=>m.role==='imp').length,3);});
test('infernal possession redirects ordinary foes but never bosses and expires',()=>{const {sim,p,enemy}=arena(0,5);let e=enemy();if(e.id%2)e=enemy();const other=enemy(e.x+20),boss=enemy();boss.boss=true;sim.activateSpecial(p);sim.gustavaxFire(p,e.x,e.y);sim.updateWorld(.01);assert.ok(e.gustavaxPossessedUntil>sim.state.time);assert.equal(boss.gustavaxPossessedUntil,undefined);e.cooldown=0;sim.updateGustavaxEnemy(e,.1);assert.ok(other.hp<10000||sim.state.enemies.some(t=>t!==e&&t.hp<10000));sim.state.time+=5;assert.equal(sim.updateGustavaxEnemy(e,.1),false);});
test('boss commands rally then team attack, with stronger manager at N5',()=>{const {sim,p,enemy}=arena(1,5),e=enemy(720);sim.activateSpecial(p);assert.equal(sim.state.allies.length,3);assert.ok(sim.state.allies.some(m=>m.role==='manager'));run(sim,p,.2,{kick:true});assert.ok(sim.state.allies.every(m=>m.mode==='rally'));run(sim,p,1,{punch:true});assert.ok(e.hp<10000);assert.ok(sim.state.allies.every(m=>m.mode==='attack'));});
test('overtime minions last four extra seconds; ultimate team survives expiry and street/save then can die',()=>{const overtime=arena(1,4);overtime.sim.activateSpecial(overtime.p);run(overtime.sim,overtime.p,7.1);assert.equal(overtime.sim.state.allies.length,2);run(overtime.sim,overtime.p,4.1);assert.equal(overtime.sim.state.allies.length,0);const {sim,p,enemy}=arena(1);sim.activateSpecial(p);run(sim,p,9.1);assert.equal(sim.state.allies.length,6);sim.enterStreet();assert.equal(sim.state.allies.length,6);sim.state.phase='clear';const restored=restoreCheckpoint(checkpoint(sim.snapshot()));assert.equal(restored.state.allies.length,6);const m=restored.state.allies[0],e=restored.spawnEnemy('remy');restored.damage(m,999,e,true);restored.updateWorld(.1);assert.ok(!restored.state.allies.includes(m));});
test('enemy hazards damage staff without treating them as player progression objects',()=>{const {sim,p,enemy}=arena(1);sim.activateSpecial(p);const m=sim.state.allies[0],e=enemy();sim.hazard(e,{x:m.x,y:m.y,radius:200,delay:0,ttl:.5,damage:20});sim.updateWorld(.1);assert.ok(m.hp<m.maxHp);assert.ok(Number.isFinite(m.hp));});
test('suplex holds and releases enemy behind; body slam damages neighbours',()=>{for(const rank of [1,2]){const {sim,p,enemy}=arena(2,rank),e=enemy(),other=enemy(640);sim.activateSpecial(p);run(sim,p,.1,{kick:true});assert.ok(e.gustavaxGrip);assert.ok(e.z>0);run(sim,p,.65,rank===2?{kick:true}:{});assert.equal(e.gustavaxGrip,null);assert.equal(e.z,0);assert.ok(e.hp<10000);assert.equal(e.x>p.x,rank===2);if(rank===2)assert.ok(other.hp<10000);}});
test('ground pound knocks down, aerial wrestling targets them, and death releases grips',()=>{const {sim,p,enemy}=arena(2,5),e=enemy();sim.activateSpecial(p);run(sim,p,.02,{dodge:true});assert.ok(e.gustavaxDownUntil>sim.state.time);run(sim,p,.1,{jump:true});assert.ok(p.z>0);run(sim,p,.7);assert.equal(p.z,0);e.x=p.x+50;sim.startGustavaxGrip(p);p.hp=0;sim.endSpecial(p);assert.equal(e.gustavaxGrip,null);assert.equal(e.z,0);});
test('champion bounces inward from ring and final projection emits arena shockwave',()=>{const {sim,p,enemy}=arena(2),e=enemy();sim.activateSpecial(p);p.x=FLOOR.right-1;run(sim,p,.03,{x:1});run(sim,p,.1,{x:1});assert.ok(p.x<FLOOR.right-20);p.x=500;e.x=580;p.specialState.elapsed=8.15;run(sim,p,.85);assert.ok(sim.state.events.some(e=>e.atlas==='gustavaxFX'&&e.cell===14));assert.equal(e.gustavaxGrip,null);});
test('all Gustavax branches resume deterministically from network snapshot',()=>{for(let b=0;b<3;b++){const {sim,p,enemy}=arena(b);enemy();sim.activateSpecial(p);run(sim,p,.2,{kick:true});const copy=new Simulation(['gustavax','jo']);copy.state=structuredClone(sim.state);copy.seed=sim.seed;copy.nextId=sim.nextId;run(sim,p,2,{punch:true});run(copy,copy.state.players[0],2,{punch:true});assert.deepEqual(copy.state,sim.state);}});
