import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../game/simulation.js';
import {applyProfile,TALENTS,spendPoint} from '../game/progression.js';
import {TRANSFORMATION_MILESTONES} from '../game/transformation-rules.js';
import {blankInput} from '../game/data.js';
function arena(branch,rank=6){const sim=new Simulation(['kikor']),p=sim.state.players[0];Object.assign(sim.state,{phase:'fight',enemies:[],props:[],spawnQueue:[]});applyProfile(p,{milestones:TRANSFORMATION_MILESTONES,talents:TALENTS.kikor.filter(n=>n.branchIndex===branch).slice(0,rank).map(n=>n.id)});Object.assign(p,{x:500,y:550,energy:100});sim.activateSpecial(p);return{sim,p};}
function run(sim,p,time,input={}){for(let t=0;t<time;t+=1/60){sim.state.time+=1/60;if(p.specialState)sim.updateSpecial(p,{...blankInput(),...input},1/60);sim.updateWorld(1/60);}}
test('Kikor has one starting point, exclusive branches and fixed durations for all ranks',()=>{assert.equal(new Simulation(['kikor']).state.players[0].progression.points,1);for(let b=0;b<3;b++)for(let r=1;r<=6;r++){const {sim,p}=arena(b,r);assert.equal(p.specialState.duration,r===6?9:r>=4?7:5);assert.equal(spendPoint(p.progression,TALENTS.kikor.find(n=>n.branchIndex===(b+1)%3).id),null);run(sim,p,9.1);assert.equal(p.specialState,null);assert.equal(sim.state.allies.length,0);}});
test('painter pots damage and leave slowing paint; charged graffiti attacks once',()=>{const {sim,p}=arena(0,3),e=sim.spawnEnemy('remy',{x:690,y:550,hp:10000,maxHp:10000,invincible:0});run(sim,p,.6,{kick:true});assert.ok(e.hp<10000);assert.ok(e.kikorPaintUntil>0);assert.equal(sim.state.kikorDrawings.length,1);run(sim,p,3);assert.equal(sim.state.kikorDrawings.length,0);});
test('ultimate painter populates walls with varied creatures and cleans army on expiry',()=>{const {sim,p}=arena(0);run(sim,p,6);assert.ok(sim.state.kikorDrawings.length>=3);assert.equal(new Set(sim.state.kikorDrawings.map(d=>d.variant)).size,3);sim.endSpecial(p);assert.equal(sim.state.kikorDrawings.length,0);});
test('summoner caps recruits and switches between ranged and protective roles',()=>{const {sim,p}=arena(1,3);sim.spawnKikorMinion(p);assert.equal(sim.spawnKikorMinion(p),false);run(sim,p,.02,{kick:true});assert.ok(sim.state.allies.every(m=>m.role===1));run(sim,p,.4);run(sim,p,.02,{kick:true});assert.ok(sim.state.allies.every(m=>m.role===2));assert.equal(sim.kikorProtect(p,20),13);});
test('participating green ally produces a clone after a kill',()=>{const {sim,p}=arena(1,5),m=sim.state.allies[0],e=sim.spawnEnemy('remy',{x:550,y:550,hp:1,invincible:0});e.kikorParticipants={[m.id]:sim.state.time};sim.damage(e,100,p,true);assert.ok(sim.state.allies.some(m=>m.clone));});
test('freeride preserves accumulated speed through wheelies and bunny hops',()=>{const {sim,p}=arena(2,5);run(sim,p,1,{x:1});const speed=p.specialState.speed;run(sim,p,.02,{x:1,punch:true,jump:true});assert.ok(p.specialState.speed>=speed);assert.ok(p.z>0);run(sim,p,.6,{x:-1});assert.equal(p.z,0);});
test('Kikor transformations replay deterministically from serialized state',()=>{for(let b=0;b<3;b++){const {sim,p}=arena(b);run(sim,p,1,{punch:true});const copy=new Simulation(['kikor']);copy.state=structuredClone(sim.state);copy.seed=sim.seed;copy.nextId=sim.nextId;run(sim,p,2,{kick:true,x:1});run(copy,copy.state.players[0],2,{kick:true,x:1});assert.deepEqual(copy.state,sim.state);}});
