import test from 'node:test';
import { applyProfile, TALENTS } from '../game/progression.js';
import assert from 'node:assert/strict';
import { Simulation } from '../game/simulation.js';
import { blankInput } from '../game/data.js';
import { neighborhoodPlan, neighborhoodChoices, cleanNeighborhood } from '../game/neighborhood-events.js';
import { NIGHT_KINDS, SCHOOL_KINDS, BUS_DOOR, ELECTRIC, VENDING, LATE_EXIT, GYM_CHOICES, bellRush, vendingRisk } from '../game/late-events.js';
import { checkpoint, restoreCheckpoint } from '../game/run-save.js';
function arena(kind,team=['jo']){const chapter=NIGHT_KINDS.includes(kind)?4:5,g=new Simulation(team,chapter,123),ledger=chapter===4?'night':'school';g.state[ledger].plan=[{stage:1,kind},{stage:3,kind:chapter===4?(kind==='cart'?'blackout':'cart'):(kind==='bell'?'photo':'bell')}];g.state.stage=1;g.enterStreet();g.state.wave=0;g.spawnWave();return g;}
function choose(g,id='accept',slot=0){const p=g.state.players[slot],c=neighborhoodChoices(g.state.neighborhoodEncounter).find(c=>c.id===id);Object.assign(p,{x:c.x,y:c.y});g.interactNeighborhood(p);}
function start(g){g.state.players.forEach((_,i)=>choose(g,'accept',i));}
function at(g,point,slot=0){const p=g.state.players[slot];Object.assign(p,{x:point.x,y:point.y,z:0,stun:0,attack:null});return g.interactNeighborhood(p);}
function win(g){g.state.enemies=[];g.state.spawnQueue=[];g.step();}

test('final chapters draw two seeded distinct events and leave boss and first street unchanged',()=>{
 for(const chapter of [4,5]){const kinds=chapter===4?NIGHT_KINDS:SCHOOL_KINDS,seen=new Set();for(let seed=0;seed<80;seed++){const plan=neighborhoodPlan(seed,chapter);assert.deepEqual(plan,neighborhoodPlan(seed,chapter));assert.ok(plan.plan.every(p=>kinds.includes(p.kind)));assert.equal(new Set(plan.plan.map(p=>p.kind)).size,2);seen.add(plan.plan.map(p=>p.kind).join());}assert.ok(seen.size>=10);const g=arena(kinds[0]);for(let stage=0;stage<6;stage++){g.state.stage=stage;g.enterStreet();assert.equal(g.state.waves.filter(w=>w.neighborhood).length,[1,3].includes(stage)?1:0);if(stage===5)assert.equal(g.state.waves.at(-1).boss,true);}}
 assert.deepEqual(cleanNeighborhood(neighborhoodPlan(1,4),1,5),neighborhoodPlan(1,5));
});
test('all eight encounters are optional with shared consent and no XP for skipping',()=>{for(const kind of [...NIGHT_KINDS,...SCHOOL_KINDS]){const g=arena(kind,['jo','yanu']);choose(g);assert.equal(g.state.neighborhoodEncounter.status,'choice');choose(g,'skip',1);assert.equal(g.state.phase,'rest');assert.equal(g.state.players[0].progression.xp,0);}});
test('bus requires both living players at the door during its window and grants no wave XP',()=>{
 const g=arena('lastBus',['jo','yanu']);start(g);const e=g.state.neighborhoodEncounter;at(g,BUS_DOOR);assert.deepEqual(e.boarded,{});e.elapsed=7;at(g,BUS_DOOR);assert.equal(e.status,'active');g.state.players[1].hp=0;at(g,BUS_DOOR,1);assert.equal(e.status,'active');g.state.players[1].hp=60;g.state.pickups.push({id:990,kind:'food',x:500,y:550});g.spawnEnemy('remy');at(g,BUS_DOOR,1);assert.equal(e.tookBus,true);assert.equal(g.state.phase,'rest');assert.equal(g.state.enemies.length,0);assert.equal(g.state.pickups.length,0);assert.equal(g.state.players[0].progression.xp,0);g.step();assert.equal(g.state.players[0].progression.xp,0);
 const h=arena('lastBus');start(h);h.state.neighborhoodEncounter.elapsed=15;at(h,BUS_DOOR);assert.equal(h.state.phase,'fight');win(h);assert.equal(h.state.phase,'rest');
});
test('bus approval is revoked when leaving the boarding area',()=>{const g=arena('lastBus',['jo','yanu']);start(g);const e=g.state.neighborhoodEncounter;e.elapsed=7;at(g,BUS_DOOR);g.state.players[0].x=200;g.updateLate(0);at(g,BUS_DOOR,1);assert.equal(e.status,'active');assert.ok(!e.boarded[1]);});
test('cart pushes in facing direction, hits once per target and breaks after three impacts',()=>{const g=arena('cart');start(g);const e=g.state.neighborhoodEncounter,p=g.state.players[0];p.facing=1;at(g,e.cart);assert.equal(e.cart.vx,620);const foes=[0,1,2].map(i=>g.spawnEnemy('remy',{x:650+i*5,y:550,invincible:0}));g.updateLate(.03);assert.equal(e.cart.impacts,3);assert.equal(e.cart.vx,0);assert.ok(foes.every(f=>f.stun>=1.5));at(g,e.cart);assert.equal(e.cart.vx,0);win(g);assert.equal(e.status,'success');});
test('blackout can be ended safely and its capped bonus requires leaving the lights off',()=>{const g=arena('blackout');start(g);at(g,ELECTRIC);win(g);assert.equal(g.state.players[0].energy,0);const h=arena('blackout');start(h);h.state.players[0].energy=80;win(h);assert.equal(h.state.players[0].energy,100);h.finishNeighborhoodWave();assert.equal(h.state.players[0].energy,100);});
test('vending shows increasing risk, requires fresh duo agreement and stops with rewards retained',()=>{
 const g=arena('vending',['jo','yanu']);start(g);const e=g.state.neighborhoodEncounter;assert.equal(vendingRisk(e),0);at(g,VENDING);assert.equal(e.attempts,0);at(g,VENDING,1);assert.equal(e.attempts,1);assert.deepEqual(g.state.players.map(p=>p.energy),[20,20]);assert.equal(vendingRisk(e),.35);assert.deepEqual(e.votes,{});at(g,LATE_EXIT);assert.equal(e.status,'success');assert.equal(g.state.players[0].progression.xp,0);
});
test('vending alarm happens once and three successful pulls cannot repeat rewards',()=>{
 const g=arena('vending');start(g);at(g,VENDING);const e=g.state.neighborhoodEncounter;e.random=0;at(g,VENDING);assert.equal(e.alarm,true);assert.equal(g.state.phase,'fight');const n=g.state.spawnQueue.length;at(g,VENDING);assert.equal(g.state.spawnQueue.length,n);assert.equal(g.state.players[0].energy,20);win(g);assert.equal(g.state.phase,'rest');
 const h=arena('vending');start(h);const f=h.state.neighborhoodEncounter;for(let i=0;i<3;i++){f.random=1600;at(h,VENDING);}assert.equal(f.status,'success');assert.equal(h.state.players[0].energy,60);at(h,VENDING);assert.equal(h.state.players[0].energy,60);
});
test('school bell is exclusively six Jualos with warning before collision and one hit per crossing',()=>{
 const g=arena('bell');start(g);const e=g.state.neighborhoodEncounter,p=g.state.players[0];e.elapsed=.5;assert.equal(bellRush(e).warning,true);assert.ok(bellRush(e).actors.every(a=>a.kind==='jualos'));assert.equal(bellRush(e).actors.length,6);p.x=200;p.y=495;p.invincible=0;const hp=p.hp;g.updateLate(.1);assert.equal(p.hp,hp);e.elapsed=1.9;p.x=200;p.y=495;const foe=g.spawnEnemy('remy',{x:200,y:495,invincible:0}),ehp=foe.hp;g.updateLate(0);assert.ok(p.hp<hp);assert.ok(foe.hp<ehp);const after=p.hp;g.updateLate(0);assert.equal(p.hp,after);assert.equal(g.state.enemies.length,1);assert.ok(g.state.events.some(e=>e.type==='schoolBell'));
 const h=arena('bell');start(h);const q=h.state.players[0];Object.assign(q,{x:200,y:495,z:45,invincible:0});h.state.neighborhoodEncounter.elapsed=1.9;const before=q.hp;h.updateLate(0);assert.equal(q.hp,before);
});
test('exam rewards only current actual skills, precise dodge, released throw and distinct special targets',()=>{
 const g=arena('exam');start(g);const p=g.state.players[0],e=g.state.neighborhoodEncounter;g.schoolAction('throw');assert.equal(p.energy,0);g.rogueOnDodge(p);assert.equal(p.energy,0);const foe=g.spawnEnemy('remy',{x:p.x+90,y:p.y,invincible:0});foe.attack={hit:false,windup:.6,elapsed:.5};g.rogueOnDodge(p);assert.equal(p.energy,15);g.rogueOnDodge(p);assert.equal(p.energy,15);
 e.elapsed=12;foe.x=p.x+25;foe.attack=null;foe.z=0;p.cooldown=0;p.grabCd=0;assert.equal(g.tryGrab(p),true);g.updateInteraction(p,true,.01,{x:-1,punch:true});g.updateInteraction(p,false,.3,{x:-1});assert.ok(e.examDone.includes(1));
 g.releaseGrab(p);e.elapsed=22;applyProfile(p,{talents:[TALENTS[p.kind][0].id]});p.energy=100;g.activateSpecial(p);const a=g.spawnEnemy('remy',{x:800,y:540,hp:999,maxHp:999}),b=g.spawnEnemy('remy',{x:850,y:540,hp:999,maxHp:999});g.damage(a,5,p,false);g.damage(a,5,p,false);assert.ok(!e.examDone.includes(2));g.damage(b,5,p,false);assert.ok(e.examDone.includes(2));win(g);assert.equal(e.status,'success');
});
test('gym choices are individual, bounded and carry the ricochet ball through checkpoint',()=>{
 const g=arena('gym',['jo','yanu']);start(g);at(g,GYM_CHOICES[0]);assert.equal(g.state.players[0].gymBalls,1);assert.equal(g.state.phase,'encounter');at(g,GYM_CHOICES[1]);assert.ok(!g.state.players[0].weapon);g.state.players[1].hp=40;at(g,GYM_CHOICES[2],1);assert.equal(g.state.players[1].hp,75);assert.equal(g.state.phase,'rest');assert.equal(g.state.players[0].progression.xp,0);
 const resumed=restoreCheckpoint(checkpoint(g.snapshot()));assert.equal(resumed.state.players[0].gymBalls,1);assert.deepEqual(resumed.state.school.plan,g.state.school.plan);resumed.state.phase='fight';const p=resumed.state.players[0];p.x=400;p.y=550;p.weapon={kind:'bat',uses:8};const foes=[500,600,700,800].map(x=>resumed.spawnEnemy('remy',{x,y:550,hp:999,maxHp:999,invincible:0}));resumed.startAttack(p,'punch');assert.equal(p.gymBalls,0);assert.equal(p.weapon.uses,8);for(let i=0;i<100;i++)resumed.updateGymBalls(1/60);assert.equal(foes.filter(f=>f.hp<999).length,3);assert.equal(resumed.state.gymProjectiles.length,0);assert.equal(resumed.throwSchoolBall(p),false);
});
test('photo heals only inside the frame, stuns enemies, and never exceeds three flashes',()=>{const g=arena('photo',['jo','yanu']);start(g);const [p,q]=g.state.players,e=g.state.neighborhoodEncounter;Object.assign(p,{x:600,y:550,hp:30,z:0});Object.assign(q,{x:300,y:550,hp:30});const foe=g.spawnEnemy('remy',{x:620,y:540});for(let i=0;i<5;i++)g.updateLate(6);assert.equal(e.photos,3);assert.equal(p.hp,75);assert.equal(q.hp,30);assert.equal(foe.stun,2.5);win(g);assert.equal(e.status,'success');});
test('late plans and outcomes survive saves; pause freezes timers and failed objectives cannot lock combat',()=>{for(const kind of [...NIGHT_KINDS,...SCHOOL_KINDS]){const g=arena(kind);g.state.phase='rest';g.state.wave=0;const raw=checkpoint(g.snapshot()),h=restoreCheckpoint(raw);assert.deepEqual(h.state.night.plan,g.state.night.plan);assert.deepEqual(h.state.school.plan,g.state.school.plan);g.state.phase='encounter';start(g);const e=g.state.neighborhoodEncounter;g.pause(true);g.step();assert.equal(e.elapsed,0);g.pause(false);if(kind==='gym')at(g,GYM_CHOICES[3]);else if(kind==='vending')at(g,LATE_EXIT);else win(g);assert.equal(g.state.phase,'rest');const again=restoreCheckpoint(checkpoint(g.snapshot()));assert.equal((NIGHT_KINDS.includes(kind)?again.state.night:again.state.school).outcomes.length,1);}});
