import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../game/simulation.js';
import {neighborhoodPlan, neighborhoodChoices, cleanNeighborhood} from '../game/neighborhood-events.js';
import {STADIUM_KINDS,RELAY_POINTS,sprinklerState} from '../game/stadium-events.js';
import {checkpoint,restoreCheckpoint} from '../game/run-save.js';
function arena(kind,team=['jo']){const g=new Simulation(team,2,123);g.state.stadium.plan=[{stage:1,kind},{stage:3,kind:kind==='coach'?'relay':'coach'}];g.state.stage=1;g.enterStreet();g.state.wave=0;g.spawnWave();return g;}
function accept(g,slot=0,id='accept'){const p=g.state.players[slot],c=neighborhoodChoices(g.state.neighborhoodEncounter).find(c=>c.id===id);Object.assign(p,{x:c.x,y:c.y});g.interactNeighborhood(p);}
function win(g){g.state.spawnQueue=[];g.state.enemies=[];g.step();}
test('stadium draws two unique seeded events and changes only two streets',()=>{const seen=new Set();for(let seed=0;seed<80;seed++){const p=neighborhoodPlan(seed,2);assert.deepEqual(p,neighborhoodPlan(seed,2));assert.equal(new Set(p.plan.map(p=>p.kind)).size,2);assert.ok(p.plan.every(p=>STADIUM_KINDS.includes(p.kind)));seen.add(p.plan.map(p=>p.kind).join());}assert.ok(seen.size>=10);const g=arena('coach');for(let stage=0;stage<6;stage++){g.state.stage=stage;g.enterStreet();assert.equal(g.state.waves.filter(w=>w.neighborhood).length,[1,3].includes(stage)?1:0);}assert.deepEqual(cleanNeighborhood(neighborhoodPlan(1,1),1,2),neighborhoodPlan(1,2));});
test('all stadium encounters require shared consent and can be skipped',()=>{for(const kind of STADIUM_KINDS){const g=arena(kind,['jo','yanu']);accept(g);assert.equal(g.state.phase,'encounter');accept(g,1,'skip');assert.equal(g.state.phase,'rest');assert.equal(g.state.stadium.outcomes[0].status,'skipped');assert.equal(g.state.players[0].progression.xp,0);}});
test('ball hits enemies, scores capped goals and adds bounded reinforcements',()=>{const g=arena('football');accept(g);const e=g.state.neighborhoodEncounter,p=g.state.players[0];p.x=560;p.y=550;const foe=g.spawnEnemy('remy',{x:640,y:550,invincible:0});const hp=foe.hp;g.hitStadiumBall(p,'kick');g.updateStadium(1/60);assert.ok(foe.hp<hp);const after=foe.hp;g.updateStadium(0);assert.equal(foe.hp,after);g.state.enemies=[];const initial=g.state.spawnQueue.length;for(let i=0;i<4;i++){Object.assign(e.ball,{x:1159,y:550,vx:900,owner:p.id});g.updateStadium(.02);}assert.equal(e.goals,3);assert.equal(g.state.pickups.filter(p=>p.amount===20).length,3);assert.equal(g.state.spawnQueue.length,initial+6);win(g);assert.equal(e.status,'success');});
test('relay passes, drops only on real damage, completes and saves one-street speed bonus',()=>{const g=arena('relay',['jo','yanu']);accept(g);accept(g,1);const e=g.state.neighborhoodEncounter,[p,q]=g.state.players;Object.assign(p,e.baton);g.interactNeighborhood(p);assert.equal(e.carrier,1);Object.assign(q,{x:p.x+30,y:p.y});g.interactNeighborhood(p);assert.equal(e.carrier,2);const beforeDamage=g.rogueBeforeDamage;g.rogueBeforeDamage=()=>0;g.damage(q,10,p,false);assert.equal(e.carrier,2);g.rogueBeforeDamage=beforeDamage;g.damage(q,10,p,false);assert.equal(e.carrier,null);q.stun=0;q.attack=null;Object.assign(q,e.baton);g.interactNeighborhood(q);assert.equal(e.carrier,null);g.updateStadium(1);g.interactNeighborhood(q);assert.equal(e.carrier,2);for(const point of RELAY_POINTS){Object.assign(q,point);q.z=0;g.updateStadium(0);}assert.equal(e.checkpoint,3);win(g);assert.equal(g.state.stadium.helpStage,2);const resumed=restoreCheckpoint(checkpoint(g.snapshot()));assert.equal(resumed.state.stadium.helpStage,2);resumed.state.stage=2;resumed.enterStreet();assert.equal(resumed.stadiumSpeedMultiplier(),1.15);const again=restoreCheckpoint(checkpoint(resumed.snapshot()));assert.equal(again.stadiumSpeedMultiplier(),1.15);again.state.stage=3;again.enterStreet();assert.equal(again.stadiumSpeedMultiplier(),1);});
test('coach enforces actual actions and rewards only once',()=>{for(const rule of ['feet','noSpecial']){const g=arena('coach');g.state.neighborhoodEncounter.rule=rule;accept(g);const p=g.state.players[0];g.startAttack(p,'kick');assert.equal(g.state.neighborhoodEncounter.failed,false);p.energy=0;g.activateSpecial(p);assert.equal(g.state.neighborhoodEncounter.failed,false);g.stadiumAction(rule==='feet'?'throw':'special');win(g);assert.equal(g.state.neighborhoodEncounter.status,'missed');assert.equal(g.state.pickups.filter(p=>p.weapon==='bat').length,0);}const g=arena('coach');accept(g);win(g);assert.equal(g.state.players[0].energy,30);assert.equal(g.state.pickups.filter(p=>p.weapon==='bat').length,1);g.finishNeighborhoodWave();assert.equal(g.state.players[0].energy,30);});
test('sprinklers warn, push both teams without damage, can be shut and reward staying active',()=>{const g=arena('sprinklers');accept(g);const e=g.state.neighborhoodEncounter,p=g.state.players[0],foe=g.spawnEnemy('remy',{x:230,y:490});e.elapsed=.5;assert.equal(sprinklerState(e).warning,true);Object.assign(p,{x:230,y:490,z:0});g.updateStadium(0);assert.equal(p.x,230);e.elapsed=1.4;const hp=p.hp;g.updateStadium(.05);assert.ok(p.x>230);assert.ok(foe.x>230);assert.equal(p.hp,hp);for(const v of [{x:350,y:490},{x:930,y:620}]){Object.assign(p,v);g.interactNeighborhood(p);}assert.equal(e.valves.length,2);assert.equal(sprinklerState(e).active,false);win(g);assert.equal(e.status,'missed');const h=arena('sprinklers');accept(h);win(h);assert.equal(h.state.players[0].energy,40);});
test('unfinished objectives never block wave completion, pause freezes events and saves preserve plans',()=>{for(const kind of STADIUM_KINDS){const g=arena(kind);const plan=JSON.stringify(g.state.stadium.plan);g.state.phase='rest';g.state.wave=0;const resumed=restoreCheckpoint(checkpoint(g.snapshot()));assert.equal(JSON.stringify(resumed.state.stadium.plan),plan);g.state.phase='encounter';accept(g);g.pause(true);const time=g.state.neighborhoodEncounter.elapsed;g.step();assert.equal(g.state.neighborhoodEncounter.elapsed,time);g.pause(false);win(g);assert.equal(g.state.phase,'rest');assert.equal(g.state.stadium.outcomes.length,1);}});
