/** Chemins des images (assets/<personnage>/ ou assets/shared/). */
import { assetRelPath } from './assetPaths.js';

export const ASSET_PATH = 'assets';

export const IMG_EXT = {
  'attaque1_regard_insomniaque (1)': 'png',
  'attaque1_regard_insomniaque (2)': 'png',
  'attaque2_cafe_turbo (1)': 'png',
  'attaque2_cafe_turbo (2)': 'png',
  'attaque2_cafe_turbo (3)': 'png',
  'attaque2_cafe_turbo (4)': 'png',
  'attaque3_fatigue_contagieuse': 'png',
  'attaque5_rage_rouge (1)': 'png',
  'attaque5_rage_rouge (2)': 'png',
  'attaque5_rage_rouge (3)': 'png',
  'attaque5_rage_rouge (4)': 'png',
  'attaque5_rage_rouge (5)': 'png',
  'bac': 'png',
  'banc': 'png',
  'barriere': 'png',
  'billets_03': 'png',
  'billets_06': 'png',
  'billets_09': 'png',
  'billets_12': 'png',
  'billets_17': 'png',
  'billets_20': 'png',
  'billets_23': 'png',
  'billets_28': 'png',
  'billets_30': 'png',
  'bouche': 'png',
  'buisson': 'png',
  'carte': 'png',
  'charge1': 'png',
  'charge2': 'png',
  'charge3': 'png',
  'charge4': 'png',
  'charlingals_attaque1': 'png',
  'charlingals_attaque2': 'png',
  'charlingals_attaque3': 'png',
  'charlingals_attaque4': 'png',
  'charlingals_marche1': 'png',
  'charlingals_marche2': 'png',
  'charlingals_marche3': 'png',
  'charlingals_marche4': 'png',
  'charlingals_mort1': 'png',
  'charlingals_special1': 'png',
  'charlingals_special2': 'png',
  'charlingals_special3': 'png',
  'charlingals_tombe1': 'png',
  'charlingals_tombe2': 'png',
  'charlingals_tombe3': 'png',
  'chateau_etang_01': 'png',
  'chateau_etang_02': 'png',
  'chateau_etang_03': 'png',
  'chateau_etang_04': 'png',
  'chateau_etang_05': 'png',
  'chateau_etang_06': 'png',
  'stade1': 'png',
  'stade2': 'png',
  'stade3': 'png',
  'stade4': 'png',
  'stade5': 'png',
  'stade6': 'png',
  'bourg1': 'png',
  'bourg2': 'png',
  'bourg3': 'png',
  'bourg4': 'png',
  'bourg5': 'png',
  'bourg6': 'png',
  'capsaran1': 'png',
  'capsaran2': 'png',
  'capsaran3': 'png',
  'capsaran4': 'png',
  'capsaran5': 'png',
  'capsaran6': 'png',
  'chene_maillard1': 'png',
  'chene_maillard2': 'png',
  'chene_maillard3': 'png',
  'chene_maillard4': 'png',
  'chene_maillard5': 'png',
  'chene_maillard6': 'png',
  'chicken': 'png',
  'chicken_gold': 'png',
  'clope1': 'png',
  'clope2': 'png',
  'clope3': 'png',
  'clope4': 'png',
  'cone': 'png',
  'cop_car': 'png',
  'cop_heli': 'png',
  'cop_kneel': 'png',
  'cop_rifle': 'png',
  'cop_rifle2': 'png',
  'cop_shoot1': 'png',
  'cop_shoot2': 'png',
  'cop_stand': 'png',
  'cop_walk1': 'png',
  'cop_walk2': 'png',
  'coup_pied (1)': 'png',
  'coup_pied (2)': 'png',
  'coup_pied (3)': 'png',
  'coup_pied (4)': 'png',
  'coup_poing (1)': 'png',
  'coup_poing (2)': 'png',
  'coup_poing (3)': 'png',
  'coup_poing (4)': 'png',
  'coup_poing (5)': 'png',
  'crate0': 'png',
  'crate1': 'png',
  'crate2': 'png',
  'destruction_golf (1)': 'png',
  'destruction_golf (2)': 'png',
  'destruction_golf (3)': 'png',
  'destruction_golf (4)': 'png',
  'entree_golf (1)': 'png',
  'entree_golf (2)': 'png',
  'entree_golf (3)': 'png',
  'entree_golf (4)': 'png',
  'gustavax_p': 'png',
  'gustavax_p - Copie': 'png',
  'gustavax_sheet': 'png',
  'guylux_attaque1': 'png',
  'guylux_attaque2': 'png',
  'guylux_attaque3': 'png',
  'guylux_attaque4': 'png',
  'guylux_marche1': 'png',
  'guylux_marche2': 'png',
  'guylux_marche3': 'png',
  'guylux_marche4': 'png',
  'guylux_mort1': 'png',
  'guylux_special1': 'png',
  'guylux_special2': 'png',
  'guylux_tombe1': 'png',
  'guylux_tombe2': 'png',
  'guylux_tombe3': 'png',
  'idle (1)': 'png',
  'idle (2)': 'png',
  'idle (3)': 'png',
  'idle (4)': 'png',
  'idle (5)': 'png',
  'incendie': 'png',
  'interdit': 'png',
  'jo_court (1)': 'png',
  'jo_court (2)': 'png',
  'jo_court (3)': 'png',
  'jo_court (4)': 'png',
  'jo_court (5)': 'png',
  'jo_court (6)': 'png',
  'jo_idle (1)': 'png',
  'jo_idle (2)': 'png',
  'jo_idle (3)': 'png',
  'jo_idle (4)': 'png',
  'jo_marche (1)': 'png',
  'jo_marche (2)': 'png',
  'jo_marche (3)': 'png',
  'jo_marche (4)': 'png',
  'jo_mort (1)': 'png',
  'jo_mort (2)': 'png',
  'jo_mort (3)': 'png',
  'jo_mort (4)': 'png',
  'jo_mort (5)': 'png',
  'jo_mort (6)': 'png',
  'jo_p': 'png',
  'jo_pied (1)': 'png',
  'jo_pied (2)': 'png',
  'jo_pied (3)': 'png',
  'jo_poing (1)': 'png',
  'jo_poing (2)': 'png',
  'jo_poing (3)': 'png',
  'jo_saute1': 'png',
  'jo_saute2': 'png',
  'jo_saute3': 'png',
  'jo_saute4': 'png',
  'jo_tombe (1)': 'png',
  'jo_tombe (2)': 'png',
  'jo_tombe (3)': 'png',
  'jo_tombe (4)': 'png',
  'jo_tombe (5)': 'png',
  'jualos_court (1)': 'png',
  'jualos_court (2)': 'png',
  'jualos_court (3)': 'png',
  'jualos_court (4)': 'png',
  'jualos_court (5)': 'png',
  'jualos_court (6)': 'png',
  'jualos_idle (1)': 'png',
  'jualos_idle (2)': 'png',
  'jualos_idle (3)': 'png',
  'jualos_idle (4)': 'png',
  'jualos_marche (1)': 'png',
  'jualos_marche (2)': 'png',
  'jualos_marche (3)': 'png',
  'jualos_marche (4)': 'png',
  'jualos_mort (1)': 'png',
  'jualos_mort (2)': 'png',
  'jualos_mort (3)': 'png',
  'jualos_mort (4)': 'png',
  'jualos_mort (5)': 'png',
  'jualos_mort (6)': 'png',
  'jualos_p': 'png',
  'jualos_pied (1)': 'png',
  'jualos_pied (2)': 'png',
  'jualos_pied (3)': 'png',
  'jualos_pied (4)': 'png',
  'jualos_poing (1)': 'png',
  'jualos_poing (2)': 'png',
  'jualos_poing (3)': 'png',
  'jualos_poing (4)': 'png',
  'jualos_saut (1)': 'png',
  'jualos_saut (2)': 'png',
  'jualos_saut (3)': 'png',
  'jualos_saut (4)': 'png',
  'jualos_tombe (1)': 'png',
  'jualos_tombe (2)': 'png',
  'jualos_tombe (3)': 'png',
  'jualos_tombe (4)': 'png',
  'jualos_tombe (5)': 'png',
  'karonux_court (1)': 'png',
  'karonux_court (2)': 'png',
  'karonux_court (3)': 'png',
  'karonux_court (4)': 'png',
  'karonux_court (5)': 'png',
  'karonux_court (6)': 'png',
  'karonux_idle (1)': 'png',
  'karonux_idle (2)': 'png',
  'karonux_idle (3)': 'png',
  'karonux_idle (4)': 'png',
  'karonux_marche (1)': 'png',
  'karonux_marche (2)': 'png',
  'karonux_marche (3)': 'png',
  'karonux_marche (4)': 'png',
  'karonux_mort (1)': 'png',
  'karonux_mort (2)': 'png',
  'karonux_mort (3)': 'png',
  'karonux_mort (4)': 'png',
  'karonux_mort (5)': 'png',
  'karonux_p': 'png',
  'karonux_pied (1)': 'png',
  'karonux_pied (2)': 'png',
  'karonux_pied (3)': 'png',
  'karonux_pied (4)': 'png',
  'karonux_poing (1)': 'png',
  'karonux_poing (2)': 'png',
  'karonux_poing (3)': 'png',
  'karonux_poing (4)': 'png',
  'karonux_saute (1)': 'png',
  'karonux_saute (2)': 'png',
  'karonux_saute (3)': 'png',
  'karonux_saute (4)': 'png',
  'karonux_tombe (1)': 'png',
  'karonux_tombe (2)': 'png',
  'karonux_tombe (3)': 'png',
  'karonux_tombe (4)': 'png',
  'karonux_tombe (5)': 'png',
  'kikor_court (1)': 'png',
  'kikor_court (2)': 'png',
  'kikor_court (3)': 'png',
  'kikor_court (4)': 'png',
  'kikor_court (5)': 'png',
  'kikor_court (6)': 'png',
  'kikor_e_p': 'png',
  'kikor_e_sheet': 'png',
  'kikor_idle (1)': 'png',
  'kikor_idle (2)': 'png',
  'kikor_idle (3)': 'png',
  'kikor_idle (4)': 'png',
  'kikor_marche (1)': 'png',
  'kikor_marche (2)': 'png',
  'kikor_marche (3)': 'png',
  'kikor_marche (4)': 'png',
  'kikor_mort (1)': 'png',
  'kikor_mort (2)': 'png',
  'kikor_mort (3)': 'png',
  'kikor_mort (4)': 'png',
  'kikor_mort (5)': 'png',
  'kikor_mort (6)': 'png',
  'kikor_p': 'png',
  'kikor_pied (1)': 'png',
  'kikor_pied (2)': 'png',
  'kikor_pied (3)': 'png',
  'kikor_pied (4)': 'png',
  'kikor_poing (1)': 'png',
  'kikor_poing (2)': 'png',
  'kikor_poing (3)': 'png',
  'kikor_poing (4)': 'png',
  'kikor_saute (1)': 'png',
  'kikor_saute (2)': 'png',
  'kikor_saute (3)': 'png',
  'kikor_saute (4)': 'png',
  'kikor_tombe (1)': 'png',
  'kikor_tombe (2)': 'png',
  'kikor_tombe (3)': 'png',
  'kikor_tombe (4)': 'png',
  'kikor_tombe (5)': 'png',
  'lampadaire_allume': 'png',
  'lampadaire_eteint': 'png',
  'level_bg_0': 'png',
  'level_bg_1': 'png',
  'lorenzo_court (1)': 'png',
  'lorenzo_court (2)': 'png',
  'lorenzo_court (3)': 'png',
  'lorenzo_court (4)': 'png',
  'lorenzo_court (5)': 'png',
  'lorenzo_court (6)': 'png',
  'lorenzo_chope': 'png',
  'lorenzo_genou1': 'png',
  'lorenzo_genou2': 'png',
  'lorenzo_idle (1)': 'png',
  'lorenzo_idle (2)': 'png',
  'lorenzo_idle (3)': 'png',
  'lorenzo_idle (4)': 'png',
  'lorenzo_marche (1)': 'png',
  'lorenzo_marche (2)': 'png',
  'lorenzo_marche (3)': 'png',
  'lorenzo_marche (4)': 'png',
  'lorenzo_mort (1)': 'png',
  'lorenzo_mort (2)': 'png',
  'lorenzo_mort (3)': 'png',
  'lorenzo_mort (4)': 'png',
  'lorenzo_mort (5)': 'png',
  'lorenzo_mort (6)': 'png',
  'lorenzo_p': 'png',
  'lorenzo_pied (1)': 'png',
  'lorenzo_pied (2)': 'png',
  'lorenzo_pied (3)': 'png',
  'lorenzo_pied (4)': 'png',
  'lorenzo_poing (1)': 'png',
  'lorenzo_poing (2)': 'png',
  'lorenzo_poing (3)': 'png',
  'lorenzo_poing (4)': 'png',
  'lorenzo_saute (1)': 'png',
  'lorenzo_saute (2)': 'png',
  'lorenzo_saute (3)': 'png',
  'lorenzo_saute (4)': 'png',
  'lorenzo_tombe (1)': 'png',
  'lorenzo_tombe (2)': 'png',
  'lorenzo_tombe (3)': 'png',
  'lorenzo_tombe (4)': 'png',
  'lorenzo_tombe (5)': 'png',
  'makouille_p': 'png',
  'makouille_sheet': 'png',
  'marche (1)': 'png',
  'marche (2)': 'png',
  'marche (3)': 'png',
  'marche (4)': 'png',
  'marche (5)': 'png',
  'mort (1)': 'png',
  'mort (2)': 'png',
  'obj_baril': 'png',
  'obj_benne': 'png',
  'obj_brasero': 'png',
  'obj_caisse': 'png',
  'obj_hydrant': 'png',
  'obj_poubelle': 'png',
  'orelsan_attaque1': 'png',
  'orelsan_attaque2': 'png',
  'orelsan_attaque3': 'png',
  'orelsan_marche1': 'png',
  'orelsan_marche2': 'png',
  'orelsan_marche3': 'png',
  'orelsan_mort1': 'png',
  'orelsan_special1': 'png',
  'orelsan_special2': 'png',
  'orelsan_tombe1': 'png',
  'orelsan_tombe2': 'png',
  'orelsan_tombe3': 'png',
  'papy_fumee1': 'png',
  'papy_fumee2': 'png',
  'papy_fumee3': 'png',
  'papy_fumee4': 'png',
  'papy_fumee5': 'png',
  'papy_fumee6': 'png',
  'papy_fumee7': 'png',
  'papy_jala_attaque1': 'png',
  'papy_jala_attaque2': 'png',
  'papy_jala_attaque3': 'png',
  'papy_jala_attaque4': 'png',
  'papy_jala_marche1': 'png',
  'papy_jala_marche2': 'png',
  'papy_jala_marche3': 'png',
  'papy_jala_mort1': 'png',
  'papy_jala_special1': 'png',
  'papy_jala_special2': 'png',
  'papy_jala_tombe1': 'png',
  'papy_jala_tombe2': 'png',
  'papy_jala_tombe3': 'png',
  'poubelle': 'png',
  'recoit_coup (1)': 'png',
  'recoit_coup (2)': 'png',
  'recoit_coup (3)': 'png',
  'recoit_coup (4)': 'png',
  'remy_attaque1': 'png',
  'remy_attaque2': 'png',
  'remy_attaque3': 'png',
  'remy_marche1': 'png',
  'remy_marche2': 'png',
  'remy_marche3': 'png',
  'remy_mort1': 'png',
  'remy_special1': 'png',
  'remy_special2': 'png',
  'remy_tombe1': 'png',
  'remy_tombe2': 'png',
  'remy_tombe3': 'png',
  'route_etang': 'png',
  'sacs_poubelle': 'png',
  'skateboard': 'png',
  'sortie_golf(1)': 'png',
  'sortie_golf(2)': 'png',
  'sortie_golf(3)': 'png',
  'sortie_golf(4)': 'png',
  'sp_jo_tornado1': 'png',
  'sp_jo_tornado2': 'png',
  'sp_jo_tornado3': 'png',
  'sp_jualos_pig1': 'png',
  'sp_jualos_pig2': 'png',
  'sp_jualos_pig3': 'png',
  'sp_karonux_1': 'png',
  'sp_karonux_explo': 'png',
  'sp_karonux_fumee': 'png',
  'sp_karonux_sleep': 'png',
  'sp_kikor_roll1': 'png',
  'sp_kikor_roll2': 'png',
  'sp_kikor_roll3': 'png',
  'sp_kikor_roll4': 'png',
  'sp_kikor_roll5': 'png',
  'sp_lorenzo_cig1': 'png',
  'sp_lorenzo_cig2': 'png',
  'sp_lorenzo_cig3': 'png',
  'sp_yanu_wolf1': 'png',
  'sp_yanu_wolf2': 'png',
  'sp_yanu_wolf3': 'png',
  'sp_yanu_wolf4': 'png',
  'sp_yanu_wolf5': 'png',
  'specials_storyboard': 'png',
  'stop': 'png',
  'titlebg': 'jpg',
  'transfo': 'png',
  'triso_attaque1': 'png',
  'triso_attaque2': 'png',
  'triso_attaque3': 'png',
  'triso_marche1': 'png',
  'triso_marche2': 'png',
  'triso_marche3': 'png',
  'triso_mort1': 'png',
  'triso_special1': 'png',
  'triso_special2': 'png',
  'triso_special3': 'png',
  'triso_tombe1': 'png',
  'triso_tombe2': 'png',
  'triso_tombe3': 'png',
  'w_barre': 'png',
  'w_batte': 'png',
  'w_bouteille': 'png',
  'w_chaine': 'png',
  'w_cle': 'png',
  'w_couteau': 'png',
  'w_flamme': 'png',
  'w_pistolet': 'png',
  'w_pompe': 'png',
  'w_tube': 'png',
  'w_uzi': 'png',
  'yanu_110': 'png',
  'yanu_court (1)': 'png',
  'yanu_court (2)': 'png',
  'yanu_court (3)': 'png',
  'yanu_court (4)': 'png',
  'yanu_court (5)': 'png',
  'yanu_court (6)': 'png',
  'yanu_idle (1)': 'png',
  'yanu_idle (2)': 'png',
  'yanu_idle (3)': 'png',
  'yanu_idle (4)': 'png',
  'yanu_marche (1)': 'png',
  'yanu_marche (2)': 'png',
  'yanu_marche (3)': 'png',
  'yanu_marche (4)': 'png',
  'yanu_meurt (1)': 'png',
  'yanu_meurt (2)': 'png',
  'yanu_meurt (3)': 'png',
  'yanu_meurt (4)': 'png',
  'yanu_meurt (5)': 'png',
  'yanu_meurt (6)': 'png',
  'yanu_p': 'png',
  'yanu_pied (1)': 'png',
  'yanu_pied (2)': 'png',
  'yanu_pied (3)': 'png',
  'yanu_pied (4)': 'png',
  'yanu_poing (1)': 'png',
  'yanu_poing (2)': 'png',
  'yanu_poing (3)': 'png',
  'yanu_poing (4)': 'png',
  'yanu_saute (1)': 'png',
  'yanu_saute (2)': 'png',
  'yanu_saute (3)': 'png',
  'yanu_saute (4)': 'png',
  'yanu_tombe (1)': 'png',
  'yanu_tombe (2)': 'png',
  'yanu_tombe (3)': 'png',
  'yanu_tombe (4)': 'png'
};

export const IMG = Object.fromEntries(
  Object.entries(IMG_EXT).map(([k, e]) => [k, `${ASSET_PATH}/${assetRelPath(k, e)}`])
);